### ISSUE TITLE
Defina o repositório como um template

### ISSUE THREAD

**Issue by atmosmaciel** [cavalcantigor/flaskeleton-api#1]
Creio que por se tratar de um skeleton e estar bem estruturado, tu poderia definir o repo como um template para indicar que outras pessoas poderão criar repositórios idênticos a partir deste e usar em seus projetos.

Mais infos: https://help.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

**Comment by cavalcantigor** [comment]
Boa ideia! Eu já tinha pensando em deixar como template, mas ainda estou tendo ideias de como torná-la um pouco mais abrangente no sentindo de ser facilmente adaptada para qualquer ideia. Farei isso em breve. Valeu!

**Comment by cavalcantigor** [comment]
Done! Fechando...
